FROM confluentinc/cp-server-connect-base:7.4.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.3
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.2.1