                                                                                                                                                                                                                                                       Table "spl.proposicao"
            Column             |            Type             | Collation | Nullable |                                                                          Default                                                                           | Storage  | Compression | Stats target |                                                                                                               Description                                                                                                                
-------------------------------+-----------------------------+-----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+-------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 pro_id                        | integer                     |           | not null | nextval('spl.proposicao_pro_id_seq'::regclass)                                                                                                             | plain    |             |              | 
 tpr_id                        | integer                     |           | not null |                                                                                                                                                            | plain    |             |              | 
 pro_numero                    | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 pro_ano                       | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 ini_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 usu_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Autoria (usuário responsável)
 pro_envio_protocolo           | timestamp without time zone |           |          |                                                                                                                                                            | plain    |             |              | Data de envio ao protocolo
 pro_protocolada               | timestamp without time zone |           |          |                                                                                                                                                            | plain    |             |              | Data em que foi aceita no/despachada do Protocolo.
 ut_id                         | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Onde a proposição está
 pro_texto                     | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_sumula                    | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_justificativa             | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_observacao                | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_id_anexada_por            | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Proposição a que foi anexada
 nod_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 pro_alternativo               | boolean                     |           | not null | false                                                                                                                                                      | plain    |             |              | Indica se a proposição está em trâmite alternativo
 pro_devolvida                 | boolean                     |           |          | false                                                                                                                                                      | plain    |             |              | Indica se a proposição foi devolvida do protocolo ao setor de criação
 est_id                        | integer                     |           | not null |                                                                                                                                                            | plain    |             |              | 
 pro_informado156              | boolean                     |           | not null | false                                                                                                                                                      | plain    |             |              | Indica se a existência da proposição já foi informada ao sistema 156 (nem todas as proposições são informadas).
 pro_resposta_pmc              | text                        |           |          |                                                                                                                                                            | extended |             |              | Resposta da Prefeitura sobre um requerimento.
 pro_introducao                | text                        |           |          | 'O Vereador, , infra-assinado(a)(s), no uso de suas atribuições legais, submete à apreciação da Câmara Municipal de Curitiba a seguinte proposição:'::text | extended |             |              | Texto de introdução à proposição
 pro_assinatura                | text                        |           |          |                                                                                                                                                            | extended |             |              | Texto com a assinatura da proposição (tipo e nome das iniciativas)
 pro_id_alvo                   | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Dependendo do tipo de proposição, poderá ter uma proposição alvo: req. urg tem a prop. que entrará em urg.; emenda tem a prop. emendada; req. de recurso tem a prop. alvo do recurso; indicações tem o projeto em que foram convertidas.
 pro_mensagem                  | character varying(20)       |           |          |                                                                                                                                                            | extended |             |              | Número da mensagem do Prefeito que originou a proposição
 pro_ultimo_tramite            | timestamp without time zone |           |          |                                                                                                                                                            | plain    |             |              | Data/hora do último trâmite (redundante)
 raz_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Razão do último trâmite dessa prop.
 pro_sumula_red_final          | text                        |           |          |                                                                                                                                                            | extended |             |              | Súmula para votação na redação final
 pro_sumula_seg_turno          | text                        |           |          |                                                                                                                                                            | extended |             |              | Súmula para votação de segundo turno
 pro_texto_red_final           | text                        |           |          |                                                                                                                                                            | extended |             |              | Texto para redação final
 pro_texto_seg_turno           | text                        |           |          |                                                                                                                                                            | extended |             |              | Texto para votação em segundo turno
 versao                        | integer                     |           | not null | 0                                                                                                                                                          | plain    |             |              | Nº de versão, para lock otimista
 pro_finalizada                | boolean                     |           | not null | false                                                                                                                                                      | plain    |             |              | Informa se a proposição já teve sua tramitação encerrada, foi fisicamente arquivada/guardada no arquivo da câmara
 pro_pesquisa_textual          | tsvector                    |           |          |                                                                                                                                                            | extended |             |              | Para fazer pesquisa textual
 pro_veto                      | spl.tipo_veto               |           | not null | 'Nenhum'::character varying                                                                                                                                | extended |             |              | Tipo de veto sofrido: Nenhum, Parcial, Total
 pro_cancelando_tramite        | boolean                     |           | not null | false                                                                                                                                                      | plain    |             |              | Indica se foi solicitado o cancelamento do último trâmite dessa proprosicao
 pro_consultas                 | integer                     |           | not null | 0                                                                                                                                                          | plain    |             |              | Quantidade de consultas a esta proposição durante o atual período (provavelmente semana)
 pro_consultas_anteriores      | integer                     |           | not null | 0                                                                                                                                                          | plain    |             |              | Quantidade de consultas a esta proposição no período (semana) passado.
 pro_similar_antiga            | text                        |           |          |                                                                                                                                                            | extended |             |              | Dados sobre proposições similares vindos do sistema anterior, especialmente de processos (proposições) não cadastrados.
 pro_informacao_quota          | text                        |           |          |                                                                                                                                                            | extended |             |              | Informação do DAP sobre outras proposições do mesmo tipo nessa legislatura ou sessão legislativa, para controle de quotas dos vereadores
 pro_data_veto_total           | date                        |           |          |                                                                                                                                                            | plain    |             |              | Data do veto total, se houver
 usu_id_final                  | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Usuário que finalizou (encerrou a tramitação)
 pro_data_final                | timestamp without time zone |           |          |                                                                                                                                                            | plain    |             |              | Data em que foi finalizada (encerrou a tramitação)
 pro_exercicio                 | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Ano de exercício a que se refere esta prestação de contas
 pro_id_origem                 | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Proposição que deu origem a esta. Usado, originalmente, para decreto legislativo de prestação de contas
 pro_codigo_envio              | character varying(8)        |           |          |                                                                                                                                                            | extended |             |              | Código de envio ao protocolo para conferência na hora de protocolar
 pro_justificativa_prorrogacao | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_pedido_presencial         | boolean                     |           | not null | false                                                                                                                                                      | plain    |             |              | 
 pro_pedido_recorrido          | character varying(14)       |           |          |                                                                                                                                                            | extended |             |              | 
 pro_codigo                    | character varying(23)       |           |          |                                                                                                                                                            | extended |             |              | Código da proposição (tamanho maior é para formatação de props não protocoladas)
 clo_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Classificação orçamentária (só usado para emenda orçamentária aditiva)
 eld_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Elemento de despesa (só usado para emenda orçamentária aditiva)
 pro_valor_orcamento           | numeric(12,2)               |           |          |                                                                                                                                                            | main     |             |              | Valor da emenda orçamentária aditiva
 org_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Órgão orçamentário (só usado para emenda orçamentária aditiva)
 uno_id                        | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Unidade orçamentária (só usado para emenda orçamentária aditiva)
 pro_autografo2_ementa         | text                        |           |          |                                                                                                                                                            | extended |             |              | Ementa para segungo autógrafo do prefeito (partes vetadas derrubadas)
 pro_autografo2_liberado       | boolean                     |           |          | false                                                                                                                                                      | plain    |             |              | Segundo autógrafo liberado?
 pro_autografo2_texto          | text                        |           |          |                                                                                                                                                            | extended |             |              | Texto para segungo autógrafo do prefeito (partes vetadas derrubadas)
 pro_autografo_ementa          | text                        |           |          |                                                                                                                                                            | extended |             |              | Ementa para autógrafo do prefeito
 pro_autografo_liberado        | boolean                     |           |          | false                                                                                                                                                      | plain    |             |              | Autógrafo liberado para visualização?
 pro_autografo_texto           | text                        |           |          |                                                                                                                                                            | extended |             |              | Texto para autógrafo do prefeito
 pro_promulgacao_texto         | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_promulgacao_ementa        | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_promulgacao_liberada      | boolean                     |           |          | false                                                                                                                                                      | plain    |             |              | 
 pro_promulgacao_norma         | character varying(12)       |           |          |                                                                                                                                                            | extended |             |              | 
 pro_solicita_urgencia         | boolean                     |           |          |                                                                                                                                                            | plain    |             |              | Esta proposição solicita urgência para si? Somente de iniciativa do Prefeito podem solicitar
 pro_urgencia                  | spl.tipo_urgencia           |           | not null | 'Nenhuma'::character varying                                                                                                                               | extended |             |              | Tem urgência? Nenhuma, Executivo, Legislativo ou Extinta
 pro_meta_fisica               | character varying(12)       |           |          |                                                                                                                                                            | extended |             |              | Meta física de emenda orçamentária aditiva; só usado para tipo de ação projeto
 eo_id                         | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 ut_id_criacao                 | integer                     |           |          |                                                                                                                                                            | plain    |             |              | 
 pro_sumula_plain              | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 pro_link_relativo             | text                        |           |          |                                                                                                                                                            | extended |             |              | 
 ver_id_ingressando            | integer                     |           |          |                                                                                                                                                            | plain    |             |              | Vereador ingressando na autoria de outra proposição, em requerimentos de ingresso na autoria apenas
 pro_sancao                    | character varying           |           |          |                                                                                                                                                            | extended |             |              | Apenas para processo ético-disciplinar. Pode ser Branda ou Severa.
 pro_sigilo                    | character varying           |           |          | 'Nenhum'::character varying                                                                                                                                | extended |             |              | 
 pro_defesa_previa             | date                        |           |          |                                                                                                                                                            | plain    |             |              | 
 pro_alegacoes_finais          | date                        |           |          |                                                                                                                                                            | plain    |             |              | 
Indexes:
    "pkproposicao" PRIMARY KEY, btree (pro_id), tablespace "index"
    "pro_pesquisa_textual_idx" gin (pro_pesquisa_textual), tablespace "index"
    "proposicao_ano_tpr_idx" btree (pro_ano, tpr_id), tablespace "index"
    "proposicao_est_id_com_urgencia_nao_finalizada_idx" btree (est_id) WHERE NOT pro_finalizada AND pro_urgencia::text <> 'Nenhuma'::text, tablespace "index"
    "proposicao_est_id_finalizada_idx" btree (est_id, pro_finalizada), tablespace "index"
    "proposicao_est_id_nao_finalizada" btree (est_id) WHERE NOT pro_finalizada, tablespace "index"
    "proposicao_ini_id_idx" btree (ini_id, pro_envio_protocolo), tablespace "index"
    "proposicao_nao_informado_tpr_idx" btree (tpr_id) WHERE NOT pro_informado156, tablespace "index"
    "proposicao_pro_codigo_idx" btree (pro_codigo), tablespace "index"
    "proposicao_pro_envio_protocolo_idx" btree (pro_envio_protocolo, pro_protocolada) WHERE pro_envio_protocolo IS NOT NULL, tablespace "index"
    "proposicao_pro_id_alvo" btree (pro_id_alvo) WHERE pro_id_alvo IS NOT NULL, tablespace "index"
    "proposicao_pro_id_anexada_por" btree (pro_id_anexada_por) WHERE pro_id_anexada_por IS NOT NULL, tablespace "index"
    "proposicao_pro_id_origem" btree (pro_id_origem) WHERE pro_id_origem IS NOT NULL, tablespace "index"
    "proposicao_pro_numero_idx" btree (pro_numero), tablespace "index"
    "proposicao_pro_protocolada_estado_idx" btree (pro_protocolada, est_id) WHERE pro_protocolada IS NOT NULL, tablespace "index"
    "proposicao_raz_id_idx" btree (raz_id), tablespace "index"
    "proposicao_tpr_est_id" btree (tpr_id, est_id), tablespace "index"
    "proposicao_tpr_id_idx" btree (tpr_id, pro_cancelando_tramite), tablespace "index"
    "proposicao_ultimo_tramite_gtl" btree (pro_ultimo_tramite) WHERE ut_id = 19 AND (tpr_id = ANY (ARRAY[51, 52])), tablespace "index"
    "proposicao_usu_id" btree (usu_id), tablespace "index"
    "proposicao_ut_id_idx" btree (ut_id), tablespace "index"
    "proposicao_ut_id_nao_finalizada_idx" btree (ut_id) WHERE NOT pro_finalizada, tablespace "index"
    "proposicao_ut_id_rascunho_idx" btree (ut_id) WHERE pro_envio_protocolo IS NULL, tablespace "index"
    "proposicao_ut_retiravel_idx" btree (ut_id, est_id) WHERE NOT pro_finalizada AND ut_id <> 724 AND est_id <> 30, tablespace "index"
Check constraints:
    "data_envio_razoavel" CHECK (pro_envio_protocolo > '1990-01-01 00:00:00'::timestamp without time zone)
    "data_protocolada_razoavel" CHECK (pro_protocolada > '1990-01-01 00:00:00'::timestamp without time zone)
    "data_tramite_razoavel" CHECK (pro_ultimo_tramite > '1990-01-01 00:00:00'::timestamp without time zone)
    "data_veto_razoavel" CHECK (pro_data_veto_total > pro_protocolada)
    "pro_sancao_chk" CHECK (pro_sancao::text = 'Branda'::text OR pro_sancao::text = 'Severa'::text)
    "pro_sigilo_chk" CHECK (pro_sigilo::text = 'Total'::text OR pro_sigilo::text = 'Parcial'::text OR pro_sigilo::text = 'Nenhum'::text)
Foreign-key constraints:
    "fk_proposicao_alvo" FOREIGN KEY (pro_id_alvo) REFERENCES spl.proposicao(pro_id)
    "fk_proposicao_anexacao" FOREIGN KEY (pro_id_anexada_por) REFERENCES spl.proposicao(pro_id)
    "fk_proposicao_classificacao_orcamentaria" FOREIGN KEY (clo_id) REFERENCES spl.classificacao_orcamentaria(clo_id)
    "fk_proposicao_elemento_despesa" FOREIGN KEY (eld_id) REFERENCES spl.elemento_despesa(eld_id)
    "fk_proposicao_entidade_externa" FOREIGN KEY (eo_id) REFERENCES spl.entidade_orcamentaria(eo_id)
    "fk_proposicao_estado" FOREIGN KEY (est_id) REFERENCES spl.estado(est_id)
    "fk_proposicao_iniciativa" FOREIGN KEY (ini_id) REFERENCES spl.iniciativa(ini_id)
    "fk_proposicao_nodo" FOREIGN KEY (nod_id) REFERENCES spl.nodo(nod_id)
    "fk_proposicao_orgao_orcamentario" FOREIGN KEY (org_id) REFERENCES spl.orgao_orcamentario(org_id)
    "fk_proposicao_origem" FOREIGN KEY (pro_id_origem) REFERENCES spl.proposicao(pro_id)
    "fk_proposicao_razao_tramite" FOREIGN KEY (raz_id) REFERENCES spl.razao_tramite(raz_id)
    "fk_proposicao_tipo_proposicao" FOREIGN KEY (tpr_id) REFERENCES spl.tipo_proposicao(tpr_id)
    "fk_proposicao_unidade_orcamentaria" FOREIGN KEY (uno_id) REFERENCES spl.unidade_orcamentaria(uno_id)
    "fk_proposicao_unidade_tramitacao" FOREIGN KEY (ut_id) REFERENCES spl.unidade_tramitacao(ut_id)
    "fk_proposicao_usuario" FOREIGN KEY (usu_id) REFERENCES geral.usuario(usu_id)
    "fk_proposicao_usuario_final" FOREIGN KEY (usu_id_final) REFERENCES geral.usuario(usu_id)
    "fk_proposicao_ut_criacao" FOREIGN KEY (ut_id_criacao) REFERENCES spl.unidade_tramitacao(ut_id)
    "fk_proposicao_vereador_ingressando" FOREIGN KEY (ver_id_ingressando) REFERENCES spl.vereador(ver_id)
Referenced by:
    TABLE "spl.assinatura" CONSTRAINT "assinatura_pro_id_fkey" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.ata_comissao" CONSTRAINT "ata_comissao_ped" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.alteracao_especial" CONSTRAINT "fk_alteracao_especial_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.alteracao_especial" CONSTRAINT "fk_alteracao_especial_proposicao_alvo_anterior" FOREIGN KEY (pro_id_alvo_anterior) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.alteracao_especial" CONSTRAINT "fk_alteracao_especial_proposicao_alvo_novo" FOREIGN KEY (pro_id_alvo_novo) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.alteracao_especial" CONSTRAINT "fk_alteracao_especial_proposicao_retirada_anterior" FOREIGN KEY (pro_id_retirada_por_anterior) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.alteracao_especial" CONSTRAINT "fk_alteracao_especial_proposicao_retirada_nova" FOREIGN KEY (pro_id_retirada_por_nova) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.anexo_publicado" CONSTRAINT "fk_anexo_publicado_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.apoio" CONSTRAINT "fk_apoio_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.arquivo" CONSTRAINT "fk_arquivo_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.emenda_valor" CONSTRAINT "fk_emenda_valor_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.fila_notificacao" CONSTRAINT "fk_fila_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.informacao" CONSTRAINT "fk_informacao_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.instrucao" CONSTRAINT "fk_instrucao_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.item_diario" CONSTRAINT "fk_item_diario_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.lei_similar" CONSTRAINT "fk_lei_similar_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.norma" CONSTRAINT "fk_norma_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.oficio_proposicao" CONSTRAINT "fk_oficio_proposicao_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.parecer" CONSTRAINT "fk_parecer_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.parecer" CONSTRAINT "fk_parecer_proposicao_anexada_por" FOREIGN KEY (pro_id_anexada_por) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.plenario" CONSTRAINT "fk_plenario_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.prazo" CONSTRAINT "fk_prazo_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.manifestacao" CONSTRAINT "fk_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.permissao_visualizacao" CONSTRAINT "fk_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.denunciado" CONSTRAINT "fk_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.proposicao" CONSTRAINT "fk_proposicao_alvo" FOREIGN KEY (pro_id_alvo) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.proposicao" CONSTRAINT "fk_proposicao_anexacao" FOREIGN KEY (pro_id_anexada_por) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.proposicao" CONSTRAINT "fk_proposicao_origem" FOREIGN KEY (pro_id_origem) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.retirada" CONSTRAINT "fk_proposicao_que_retira" FOREIGN KEY (pro_id_retirador) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.retirada" CONSTRAINT "fk_proposicao_retirada" FOREIGN KEY (pro_id_retirado) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.proposicao_similar" CONSTRAINT "fk_proposicao_similar_anterior" FOREIGN KEY (pro_id_anterior) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.proposicao_similar" CONSTRAINT "fk_proposicao_similar_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
    TABLE "spl.ranking" CONSTRAINT "fk_ranking_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.seguidor_proposicao" CONSTRAINT "fk_seguidor_proposicao_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.tramite_pmc" CONSTRAINT "fk_tramite_pmc_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id)
    TABLE "spl.tramite" CONSTRAINT "fk_tramite_proposicao" FOREIGN KEY (pro_id) REFERENCES spl.proposicao(pro_id) ON DELETE CASCADE
Triggers:
    ti_proposicao_codigo BEFORE INSERT ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.fti_proposicao_codigo()
    tiu_0_white_proposicao BEFORE INSERT OR UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftiu_0_white_proposicao()
    tiu_proposicao BEFORE INSERT OR UPDATE ON spl.proposicao FOR EACH ROW WHEN (new.clo_id IS NOT NULL AND (new.pro_meta_fisica IS NULL OR btrim(new.pro_meta_fisica::text) = ''::text)) EXECUTE FUNCTION spl.ftiu_proposicao()
    tiu_proposicao_req_cpi BEFORE INSERT OR UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftiu_req_cpi()
    tiu_proposicao_sumula BEFORE INSERT OR UPDATE OF pro_sumula ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftiu_proposicao_sumula()
    tiu_proposicao_textual BEFORE INSERT OR UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftiu_proposicao_textual()
    tu_proposicao BEFORE UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftu_proposicao()
    tu_proposicao_0 BEFORE UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftu_proposicao_0()
    tu_proposicao_codigo BEFORE UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftu_proposicao_codigo()
    tu_proposicao_link AFTER UPDATE OF pro_codigo, est_id, pro_urgencia ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION spl.ftu_proposicao_link()
    tz_audit_spl_proposicao AFTER INSERT OR DELETE OR UPDATE ON spl.proposicao FOR EACH ROW EXECUTE FUNCTION auditoria.f_audit_spl_proposicao()
Tablespace: "data"
Access method: heap

